import os
from google import genai
from google.genai import types

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

MIT_LICENSE = """MIT License

Copyright (c) 2024 {user}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT."""

def _call_gemini(prompt: str) -> str:
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=prompt
    )
    return response.text.strip()

def _clean_html(text: str) -> str:
    """Remove markdown code blocks if Gemini adds them"""
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
    if text.endswith("```"):
        text = text.rsplit("```", 1)[0]
    return text.strip()

def generate_app(brief: str, checks: list, attachments: list) -> str:
    attachment_info = "".join(
        f"\n- {a['name']}: {a['url']}" for a in attachments
    )
    prompt = f"""You are an expert frontend developer.
Generate a single complete self-contained index.html file.

BRIEF:
{brief}

CHECKS THAT MUST PASS (JavaScript expressions evaluated in browser):
{chr(10).join(f'- {c}' for c in checks)}

ATTACHMENTS:
{attachment_info if attachment_info else 'None'}

RULES:
- Return ONLY raw HTML, no markdown, no code blocks, no explanation
- Single file, all libraries from CDN
- Must work on GitHub Pages (static only)
- Every check above must pass

Generate index.html now:"""
    return _clean_html(_call_gemini(prompt))

def generate_readme(brief: str, task: str, app_code: str) -> str:
    prompt = f"""Write a professional README.md for this project.

Task: {task}
Brief: {brief}

Static web app deployed on GitHub Pages, generated by LLM.

Sections: ## Summary, ## Setup, ## Usage, ## Code Explanation, ## License

Return only markdown, no explanation."""
    return _call_gemini(prompt)

def generate_app_revision(brief: str, checks: list,
                          attachments: list, existing_code: str) -> str:
    prompt = f"""You are an expert frontend developer.
Revise this existing HTML app based on new requirements.

EXISTING CODE:
{existing_code}

NEW BRIEF:
{brief}

NEW CHECKS THAT MUST PASS:
{chr(10).join(f'- {c}' for c in checks)}

RULES:
- Return ONLY complete revised HTML, no markdown, no explanation
- Keep everything that works, only change what's needed

Generate revised index.html now:"""
    return _clean_html(_call_gemini(prompt))
