# llm_helper.py
import google.generativeai as genai
import os

genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
model = genai.GenerativeModel("gemini-2.0-flash")

MIT_LICENSE = """MIT License

Copyright (c) 2024 {user}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT."""

def generate_app(brief: str, checks: list, 
                 attachments: list) -> str:
    """Ask Gemini to generate a complete index.html"""
    
    # format attachments for the prompt
    attachment_info = ""
    for att in attachments:
        attachment_info += f"\n- {att['name']}: available at URL {att['url']}"
    
    prompt = f"""You are an expert frontend developer.
Generate a single complete self-contained index.html file.

BRIEF:
{brief}

CHECKS THAT MUST PASS (these are JavaScript expressions 
evaluated in the browser — your code must make each one true):
{chr(10).join(f'- {c}' for c in checks)}

ATTACHMENTS AVAILABLE:
{attachment_info if attachment_info else 'None'}

STRICT RULES:
- Return ONLY the raw HTML, nothing else
- No markdown, no code blocks, no explanation
- Single file, no external files
- Load all libraries from CDN
- Must work on GitHub Pages (static hosting only)
- Every single check above must pass

Generate the complete index.html now:"""

    response = model.generate_content(prompt)
    
    # clean up in case Gemini adds markdown code blocks
    html = response.text.strip()
    if html.startswith("```"):
        html = html.split("\n", 1)[1]  # remove first line
    if html.endswith("```"):
        html = html.rsplit("```", 1)[0]  # remove last ```
    
    return html.strip()

def generate_readme(brief: str, task: str, 
                    app_code: str) -> str:
    """Ask Gemini to generate a professional README"""
    
    prompt = f"""Write a professional README.md for this project.

Task: {task}
Brief: {brief}

The project is a static web app deployed on GitHub Pages.
Generated by an LLM based on the brief above.

Include these sections:
## Summary
## Setup  
## Usage
## Code Explanation
## License

Keep it concise and professional.
Return only the markdown, no explanation."""

    response = model.generate_content(prompt)
    return response.text.strip()

def generate_app_revision(brief: str, checks: list,
                          attachments: list,
                          existing_code: str) -> str:
    """Ask Gemini to revise existing app based on new brief"""
    
    prompt = f"""You are an expert frontend developer.
Revise the existing HTML app based on the new requirements.

EXISTING CODE:
{existing_code}

NEW BRIEF:
{brief}

NEW CHECKS THAT MUST PASS:
{chr(10).join(f'- {c}' for c in checks)}

STRICT RULES:
- Return ONLY the complete revised HTML, nothing else
- No markdown, no code blocks, no explanation  
- Keep everything that already works
- Only add or change what the new brief requires

Generate the revised index.html now:"""

    response = model.generate_content(prompt)
    html = response.text.strip()
    if html.startswith("```"):
        html = html.split("\n", 1)[1]
    if html.endswith("```"):
        html = html.rsplit("```", 1)[0]
    return html.strip()